version: '3.4'

services:
  db:
    image: mysql:5.7
    ports: 
      - "3307:3306"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
    volumes:
       - dbdata:/var/lib/mysql
    restart: always

  inventoryapi:
    restart: on-failure  
    depends_on:
        - db
        - rabbitmq
    environment:
      - RABBIT_HOSTNAME=rabbitmq
      - ORDERS_EXCHANGE=orders
      - SCANNER_EXCHANGE=scanner
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: InventoryAPI/Dockerfile
    ports:
      - "5001:80"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#    - ./RabbitMQ/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
    dbdata: